name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm test
  e2e:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - name: Fix Expo dependencies
      run: npx expo install --fix
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: gem install cocoapods
    - name: Build iOS app for Detox
      run: npx detox build --configuration ios.sim.debug
    - name: Install applesimutils
      run: brew install wix/brew/applesimutils
    - name: Start Metro server
      run: npm start &
    - name: Run e2e tests
      run: npx detox test --configuration ios.sim.debug --headless --record-videos failing --take-screenshots failing